sexual_keywords = [
    'abstinence',
    'anal sex',
    'asymptomatic',
    'barrier methods',
    'bacterial vaginosis',
    'bisexual',
    'candidiasis',
    'cervical cancer',
    'chancroid',
    'chlamydia',
    'circumcision',
    'condom',
    'consent',
    'contraception',
    'crabs',
    'delayed ejaculation',
    'depot medroxyprogesterone acetate',
    'digital stimulation',
    'douching',
    'dyspareunia',
    'ectopic pregnancy',
    'erectile dysfunction',
    'exposure prophylaxis',
    'female condom',
    'fertility awareness',
    'fetishism',
    'genital herpes',
    'herpes',
    'genital warts',
    'gonorrhea',
    'heterosexual',
    'hiv',
    'homosexual',
    'hpv',
    'human immunodeficiency virus',
    'human papillomavirus',
    'hymen',
    'intercourse',
    'intrauterine device',
    'lesbian',
    'masturbation',
    'menopause',
    'menstruation',
    'microbicides',
    'morning-after pill',
    'nonoxynol-9',
    'oral sex',
    'orgasm',
    'ovulation',
    'pelvic inflammatory disease',
    'penis',
    'performance anxiety',
    'perimenopause',
    'polycystic ovary syndrome',
    'pregnancy',
    'premature ejaculation',
    'prostate cancer',
    'pubic lice',
    'rape',
    'reproductive health',
    'risk factors',
    'safe sex',
    'safety tips',
    'scabies',
    'sexual abuse',
    'sexual dysfunction',
    'sexual health',
    'sexual harassment',
    'sexual orientation',
    'sexual pain disorders',
    'sexual pleasure',
    'sexual problems',
    'sexual violence',
    'sexually transmitted disease',
    'syphilis',
    'transgender',
    'trichomoniasis',
    'vaginal dryness',
    'vaginal ring',
    'vaginitis',
    'vulva',
    'withdrawal method'
]